FROM wazuh/wazuh-certs-generator:0.0.1

LABEL IMAGE="security-wazuh-certs-generator"
LABEL VERSION="latest"
LABEL CI_IGNORE="False"

# this container is just a workaround as our build script does not support specifying dockerhub containers in helm charts directly
