---
apiVersion: v1
appVersion: "2.5.0-nninteractive_v1.0"
description: Standalone nnInteractive inference server
name: nninteractive-server
version: "0.0.0"
keywords:
- kaapanaapplication
- kaapanaexperimental
annotations:
  ui-visible-name: "nnInteractive Server"
