---
global:
  pull_policy_images: "IfNotPresent"

nninteractive:
  image: ghcr.io/mic-dkfz/nninteractive-server
  tag: 2.5.0-nninteractive_v1.0
  port: 1527
  apiKey: ""
  gpuCount: 1
  memoryRequest: 6Gi
  memoryLimit: 16Gi
  extraArgs: []
