FROM local-only/base-installer:latest

LABEL IMAGE="dag-advanced-collect-metadata-federated"
LABEL VERSION="0.1.0"
LABEL BUILD_IGNORE="False"

COPY files/dag_advanced_collect_metadata_federated.py /kaapana/tmp/dags/
COPY files/advanced_collect_metadata_federated /kaapana/tmp/dags/advanced_collect_metadata_federated