---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-broker-credentials
  namespace: {{ .Values.global.services_namespace }}
type: Opaque
data:
  NODE_USER: {{ .Values.global.credentials_node_user | default "" | b64enc }}
  NODE_PASSWORD: {{ .Values.global.credentials_node_password | default "" | b64enc }}
  ca.pem: {{ .Values.global.credentials_ssl_cafile | default "" | b64enc }}
  client-cert.pem: {{ .Values.global.credentials_ssl_client_cert | default "" | b64enc }}
  client-key.pem: {{ .Values.global.credentials_ssl_client_key | default "" | b64enc }}
