FROM local-only/dag-installer:0.1.0

LABEL IMAGE="dag-doccano-image-tagging"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY dags/dag_service_parse_doccano_tokens.py /tmp/dags/
COPY dags/dag_study_ids_to_doccano.py /tmp/dags/

COPY dags/doccano /tmp/dags/doccano

COPY executables/doccano_processing /tmp/executables/doccano_processing
