"""Setup script to auto-copy schemas during installation."""

from pathlib import Path

from setuptools import setup
from setuptools.command.build_py import build_py


class BuildWithSchemas(build_py):
    """Custom build that copies schemas before building."""

    def run(self):
        # Copy schemas from workflow-api
        self._copy_schemas()

        # Continue with normal build
        super().run()

    def _copy_schemas(self):
        """Copy schemas.py from workflow-api to workflow_cli package."""

        # Source: workflow-api service schemas
        source = (
            Path(__file__).parents[2]
            / "services"
            / "base"
            / "workflow-api"
            / "docker"
            / "files"
            / "app"
            / "schemas.py"
        )

        # Destination: workflow_cli package
        dest = Path(__file__).parent / "workflow_cli" / "schemas.py"

        if not source.exists():
            print(f"Warning: Source schemas not found: {source}")
            return

        # Copy with comment header
        content = source.read_text()
        header = '''"""
Schemas for workflow validation and API communication.

NOTE: This file is copied from services/base/workflow-api/docker/files/app/schemas.py
during package build. The workflow-api service is the source of truth.

DO NOT EDIT THIS FILE DIRECTLY - changes will be overwritten on next build.
"""

'''

        dest.write_text(header + content)


if __name__ == "__main__":
    setup(cmdclass={"build_py": BuildWithSchemas})
