FROM local-only/base-installer:latest

LABEL IMAGE="dag-wsiconv"
LABEL VERSION="0.1.0"
LABEL BUILD_IGNORE="False"

COPY files/dag_wsiconv.py /kaapana/tmp/dags/
COPY files/wsiconv /kaapana/tmp/dags/wsiconv