repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.4
    hooks:
      - id: ruff-check
        args: [--config, ci/ci-code/lint/ruff-quality.toml, --fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: local
    hooks:
      - id: helm-lint
        name: helm lint
        entry: ci/ci-code/lint/helm_lint.sh
        language: python
        require_serial: true
        files: (^|/)(Chart\.yaml|requirements\.yaml|values\.yaml|templates/.*)$
  - repo: local
    hooks:
      - id: ui-lint
        name: ESLint/Prettier (strict)
        entry: ci/ci-code/lint/ui_lint.sh --strict
        language: system
        files: \.(ts|mts|tsx|vue)$
        require_serial: true
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.15.1
    hooks:
      - id: hadolint
        args: [--failure-threshold, style]
