repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.4
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter, markdown]
  - repo: local
    hooks:
      - id: ui-lint
        name: ESLint/Prettier
        entry: ci/ci-code/lint/ui_lint.sh
        language: system
        files: \.(ts|mts|tsx|vue)$
