FROM wazuh/wazuh-manager:4.3.9

LABEL IMAGE="security-wazuh-manager"
LABEL VERSION="0.0.1"
LABEL CI_IGNORE="False"

# this container is just a workaround as our build script does not support specifying dockerhub containers in helm charts directly
