FROM wazuh/wazuh-dashboard:4.3.9

LABEL IMAGE="security-wazuh-dashboard"
LABEL VERSION="latest"
LABEL CI_IGNORE="False"

# this container is just a workaround as our build script does not support specifying dockerhub containers in helm charts directly
