---
global:
    pull_policy_images: "IfNotPresent"

extension_params:
    display_name:
        default: "-"
        definition: This name will be used in lists in the user interface.
        type: string
        value: ""
    service_secret:
        default: true
        definition: Install the secret for system-wide functionalities like installing a new workflow extension
        type: boolean
        value: ""
    project_secret:
        default: true
        definition: Install the secret in the selected project for pulling processing-containers
        type: boolean
        value: ""
    custom_registry_url:
        default: "https://"
        definition: Absolute registry URL <scheme>://<domain>:<port>//<path>
        type: string
        value: ""
    credentials_custom_registry_username:
        default: ""
        definition: Registry Username
        type: string
        value: ""
    credentials_custom_registry_password:
        default: ""
        definition: Registry Password or Access Token
        type: string
        value: ""
    test_pull_image:
        default: "-"
        definition: "Image to test pull access (<regURL>/<name>:<version>). If '-', test is skipped."
        type: string
        value: ""
