FROM local-only/base-installer:latest

LABEL IMAGE="dag-body-and-organ-analysis"
LABEL VERSION="0.1.3"
LABEL BUILD_IGNORE="False"

COPY files/dag_body_and_organ_analysis.py /kaapana/tmp/dags/
COPY files/body_and_organ_analysis /kaapana/tmp/dags/body_and_organ_analysis