"""add conditional unique constraint

Revision ID: beab7a9f4fad
Revises: fa8abfc02de3
Create Date: 2026-03-02 13:41:24.681442

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "beab7a9f4fad"
down_revision: Union[str, None] = "fa8abfc02de3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    access_level_enum = sa.Enum("private", "project", name="access_level_enum")

    # 1️⃣ create enum type
    access_level_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "dataset",
        sa.Column(
            "access_level",
            access_level_enum,
            nullable=False,
            server_default="project",
        ),
    )
    op.drop_constraint("dataset_project_id_name_key", "dataset", type_="unique")
    op.create_index(
        "unique_private_access",
        "dataset",
        ["project_id", "name", "username"],
        unique=True,
        postgresql_where=sa.text("access_level = 'private'"),
    )
    op.create_index(
        "unique_project_access",
        "dataset",
        ["project_id", "name"],
        unique=True,
        postgresql_where=sa.text("access_level = 'project'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_project_access",
        table_name="dataset",
        postgresql_where=sa.text("access_level = 'project'"),
    )
    op.drop_index(
        "unique_private_access",
        table_name="dataset",
        postgresql_where=sa.text("access_level = 'private'"),
    )
    op.create_unique_constraint(
        "dataset_project_id_name_key", "dataset", ["project_id", "name"]
    )
    op.drop_column("dataset", "access_level")
    # ### end Alembic commands ###
