"""v0-6-0

Revision ID: fa8abfc02de3
Revises: e689ab05516a
Create Date: 2025-12-09 10:55:09.009490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa8abfc02de3'
down_revision: Union[str, None] = 'e689ab05516a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installed_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('friendly_name', sa.String(length=255), nullable=False),
    sa.Column('models_name', sa.String(length=255), nullable=False),
    sa.Column('task_ids', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('instance_name', sa.String(length=255), nullable=True),
    sa.Column('model_network_trainer', sa.String(length=255), nullable=True),
    sa.Column('model_plan', sa.String(length=255), nullable=True),
    sa.Column('task_url', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('input_modalities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body_part', sa.String(length=255), nullable=True),
    sa.Column('targets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_mode', sa.String(length=50), nullable=True),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('friendly_name')
    )
    op.create_index(op.f('ix_installed_models_project_id'), 'installed_models', ['project_id'], unique=False)
    op.alter_column('dataset', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('identifier2dataset', 'dataset',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('identifier2dataset_dataset_fkey', 'identifier2dataset', type_='foreignkey')
    op.create_foreign_key(None, 'identifier2dataset', 'dataset', ['dataset'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'identifier2dataset', type_='foreignkey')
    op.create_foreign_key('identifier2dataset_dataset_fkey', 'identifier2dataset', 'dataset', ['dataset'], ['id'], ondelete='CASCADE')
    op.alter_column('identifier2dataset', 'dataset',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dataset', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_index(op.f('ix_installed_models_project_id'), table_name='installed_models')
    op.drop_table('installed_models')
    # ### end Alembic commands ###
