FROM local-only/base-installer:latest

LABEL IMAGE="dag-prepare-gt"
LABEL VERSION="0.0.0"
LABEL CI_IGNORE="False"

COPY files/dag_prepare_gt.py /kaapana/tmp/dags/
COPY files/prepare_gt /kaapana/tmp/dags/prepare_gt