# generated by datamodel-codegen:
#   filename:  IOChannel.schema.json

from __future__ import annotations

from .IOMount_schema import IOMount
from .IOVolume_schema import IOVolume


class IOChannel(IOMount, IOVolume):
    pass
