# generated by datamodel-codegen:
#   filename:  ProcessingContainer.schema.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel

from . import ContainerEnvVar_schema, IOMount_schema, Resources_schema


class ProcessingContainer(BaseModel):
    name: str
    description: str
    command: List[str]
    inputs: List[IOMount_schema.IOMount]
    outputs: List[IOMount_schema.IOMount]
    env: List[ContainerEnvVar_schema.ContainerEnvVar]
    resources: Optional[Resources_schema.Resources] = None
