# generated by datamodel-codegen:
#   filename:  Resources.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class Limits(BaseModel):
    cpu: Optional[str] = None
    memory: Optional[str] = None


class Requests(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cpu: Optional[str] = None
    memory: Optional[str] = None


class Resources(BaseModel):
    limits: Optional[Limits] = None
    requests: Optional[Requests] = None
