# generated by datamodel-codegen:
#   filename:  ScaleRule.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Optional

from pydantic import BaseModel, Field


class Type(Enum):
    limit = 'limit'
    request = 'request'


class Mode(Enum):
    sum = 'sum'
    max_file_size = 'max_file_size'


class ScaleRule(BaseModel):
    complexity: Annotated[str, Field(pattern='^[-+]?\\d*(\\.\\d+)?\\*?n(\\*\\*\\d+)?$')]
    type: Type
    mode: Mode
    target_dir: Optional[str] = None
    target_regex: Optional[str] = None
    target_glob: Optional[str] = None
