# generated by datamodel-codegen:
#   filename:  TaskInstance.schema.json

from __future__ import annotations

from typing import List, Optional

from . import IOChannel_schema
from .ProcessingContainer_schema import ProcessingContainer
from .Task_schema import Task


class TaskInstance(Task, ProcessingContainer):
    inputs: Optional[List[IOChannel_schema.IOChannel]] = None
    outputs: Optional[List[IOChannel_schema.IOChannel]] = None
