FROM local-only/dag-installer:0.1.0

LABEL IMAGE="dag-extract-scanparameters"
LABEL VERSION="0.1.0-vdev"
LABEL CI_IGNORE="False"

COPY dags/dag_extract_scanparameter.py /tmp/dags/
COPY dags/extract_scanparameter /tmp/dags/extract_scanparameter