FROM busybox:1.31

LABEL IMAGE="dag-radiomics"
LABEL VERSION="1.0.0"
LABEL CI_IGNORE="False"

COPY dags/dag_radiomics_dcmseg.py /workflows/dags/
COPY dags/radiomics /workflows/dags/radiomics

CMD ["cp","-rf","/workflows/.","/mount_data/"]