import os

DICOMWEB_BASE_URL = os.environ["DICOMWEB_BASE_URL"]
DICOMWEB_BASE_URL_WADO_URI = os.environ["DICOMWEB_BASE_URL_WADO_URI"]

DWF_IDENTITY_OPENID_CONFIG_URL = os.environ["DWF_IDENTITY_OPENID_CONFIG_URL"]
DWF_IDENTITY_OPENID_CLIENT_ID = os.environ["DWF_IDENTITY_OPENID_CLIENT_ID"]