# generated by datamodel-codegen:
#   filename:  IOChannel.schema.json

from __future__ import annotations

from task_api.processing_container.pc_models.IOMount_schema import IOMount
from task_api.processing_container.task_models.IOVolume_schema import IOVolume


class IOChannel(IOMount, IOVolume):
    """
    Binds an IOMount in the container to an IOVolume in external storage.
    """
