# generated by datamodel-codegen:
#   filename:  IOVolume.schema.json

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, ConfigDict
from task_api.processing_container.pc_models import ScaleRule_schema
from kubernetes import client as k8sclient


class HostPathVolume(BaseModel):
    host_path: str


class IOVolume(BaseModel):
    """
    Represents a storage location for input/output data.
    """

    name: str
    scale_rule: Optional[ScaleRule_schema.ScaleRule] = None
    input: Union[k8sclient.V1Volume, HostPathVolume]

    model_config = ConfigDict(arbitrary_types_allowed=True)
