# generated by datamodel-codegen:
#   filename:  TaskInstance.schema.json

from __future__ import annotations

from typing import List, Optional, Union

from task_api.processing_container.task_models import IOChannel_schema
from task_api.processing_container.task_models.Task_schema import Task
from task_api.processing_container.pc_models.TaskTemplate_schema import TaskTemplate
from task_api.processing_container.pc_models.TaskTemplateEnv_schema import (
    TaskTemplateEnv,
)
from task_api.processing_container.task_models.TaskEnvVar import TaskEnvVar


class TaskInstanceEnv(TaskTemplateEnv, TaskEnvVar):
    pass


class TaskInstance(Task, TaskTemplate):
    """
    A resolved task, created by merging the Task definition with its associated TaskTemplate.
    """

    inputs: Optional[List[IOChannel_schema.IOChannel]] = None
    outputs: Optional[List[IOChannel_schema.IOChannel]] = None
    env: Optional[List[TaskInstanceEnv]] = []
