# generated by datamodel-codegen:
#   filename:  TaskRun.schema.json

from __future__ import annotations

from task_api.processing_container.task_models.TaskInstance_schema import TaskInstance


class TaskRun(TaskInstance):
    """
    Execution record of a TaskInstance. Includes runtime metadata to track and identify the actual container or pod running the task.
    """

    id: str
    mode: str
