{{- $ns := .Values.global.services_namespace }}

############################
# ServiceAccount (always)
############################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail-serviceaccount
  namespace: {{ $ns }}
---
############################
# RBAC
############################
{{- if not .Values.global.managed_kubernetes }}

# Self-managed cluster: full ClusterRole + ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-watcher-promtail
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "nodes", "nodes/proxy", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-watcher-promtail-binding
subjects:
- kind: ServiceAccount
  name: promtail-serviceaccount
  namespace: {{$ns }}
roleRef:
  kind: ClusterRole
  name: pod-watcher-promtail
  apiGroup: rbac.authorization.k8s.io

{{- else }}


# Managed cluster: namespace-scoped Role + RoleBinding (no cluster-scoped resources)
{{- range $all_ns := .Values.global.all_managed_namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-watcher-promtail
  namespace: {{ $all_ns }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-watcher-promtail-binding
  namespace: {{ $all_ns }}
subjects:
- kind: ServiceAccount
  name: promtail-serviceaccount
  namespace: {{$ns }}
roleRef:
  kind: Role
  name: pod-watcher-promtail
  apiGroup: rbac.authorization.k8s.io

{{- end }}

{{- end }}