/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveProjectApplications: typeof import('./src/components/ActiveProjectApplications.vue')['default']
    AddSoftwareToProject: typeof import('./src/components/AddSoftwareToProject.vue')['default']
    AddUserToProject: typeof import('./src/components/AddUserToProject.vue')['default']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    copy: typeof import('./src/components/CreateNewProjectForm copy.vue')['default']
    CreateNewProjectForm: typeof import('./src/components/CreateNewProjectForm.vue')['default']
    ExecutableWorkflows: typeof import('./src/components/ExecutableWorkflows.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LaunchApplication: typeof import('./src/components/LaunchApplication.vue')['default']
    MultiinstallableApplications: typeof import('./src/components/MultiinstallableApplications.vue')['default']
    ProjectUsers: typeof import('./src/components/ProjectUsers.vue')['default']
    RequirePermissions: typeof import('./src/components/RequirePermissions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SectionHeader: typeof import('./src/components/SectionHeader.vue')['default']
    SectionTable: typeof import('./src/components/SectionTable.vue')['default']
  }
}
