global:
  services_namespace: "services"
  registry_url: ""
  kaapana_build_version: ""
  pull_policy_images: "Always"
  storage_node: "storage"

kaapana_database:
  admin: false
  postgres_user: "postgres"
  postgres_password: "postgres"
  postgres_db: "postgres"
  appName: "extension-manager"
