[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "kaapana-containers"
version = "0.1.0"
description = "A library with utils to deal with containers and registries"
authors = [
    { name="Your Name", email="your.email@example.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pydantic>=2.0",
    "jsonschema>=4.24.0",
    "typer>=0.16.0",
    "docker>=7.1.0",
    "kubernetes>=25.0.0",
    "httpx>=0.25.0",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0",
    "pytest-asyncio>=0.23",
    "pytest-xdist>=3.0",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"