FROM docker.io/opensearchproject/opensearch:2.6.0

LABEL IMAGE="opensearch"
LABEL VERSION="2.6.0"
LABEL CI_IGNORE="False"

# The OpenSearch Docker image already runs as a non-root user opensearch (uid 1000) 