FROM local-only/dag-installer:latest

LABEL IMAGE="dag-mhub-models-workflow"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY files/ /temp/ 

# COPY files/dags/dag_mhub_models.py /temp/dags/
# COPY files/dags/mhub /temp/dags/mhub
# COPY files/mounted_scripts/ 