FROM local-only/base-installer:latest

LABEL IMAGE="dag-mhub-models-workflow"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY files/ /kaapana/tmp/ 

# COPY files/dags/dag_mhub_models.py /kaapana/tmp/dags/
# COPY files/dags/mhub /kaapana/tmp/dags/mhub
# COPY files/mounted_scripts/ 