FROM local-only/dag-installer:latest

LABEL IMAGE="dag-installer-template"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="True"

COPY files/templates /temp/dags/templates
COPY files/dag_template.py /temp/dags/