FROM local-only/dag-installer:latest

LABEL IMAGE="dag-otsus-method"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY files/dag_otsus_method.py /tmp/dags/
COPY files/otsus-method/OtsusMethodOperator.py /tmp/dags/otsus_method/