{
 "title": "API Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "custom_job_name",
    "label": "Backend",
    "query": {
     "query": "label_values(http_requests_total,custom_job_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requets per Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(http_requests_total{custom_job_name=\"$custom_job_name\"}[1m])",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{custom_job_name=\"$custom_job_name\",handler!=\"none\"} / http_request_duration_seconds_count",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{custom_job_name=\"$custom_job_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(process_cpu_seconds_total{custom_job_name=\"$custom_job_name\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}