{
 "title": "Operator Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "custom_job_name", "label": "custom_job_name", "query": { "query": "label_values(custom_job_name)" } },
   {
    "name": "job",
    "label": "Scrape Job",
    "query": {
     "query": "label_values({job=\"kubernetes-pods\"},job)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kubernetes_pod_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kubernetes_namespace)"
    }
   },
   { "name": "ds_prometheus", "query": "prometheus" },
   { "name": "hostname", "label": "Hostname", "query": { "query": "label_values(Hostname)" } },
   {
    "name": "nodename",
    "label": "Datasource Node-Exporter",
    "query": {
     "query": "label_values(node_uname_info,nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   { "name": "gpu", "label": "GPU", "query": { "query": "label_values(gpu)" } }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{custom_job_name=~\"$custom_job_name\", kubernetes_namespace=~\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{custom_job_name}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "up{custom_job_name=~\"$custom_job_name\", kubernetes_namespace=~\"$namespace\", job=\"$job\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{custom_job_name}} - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU time usage split by state, normalized across all CPU cores",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\", instance=\"$node\"}[$__rate_interval])) / scalar(count(count by(cpu) (node_cpu_seconds_total{instance=\"$node\"})))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\", instance=\"$node\"}[$__rate_interval])) / scalar(count(count by(cpu) (node_cpu_seconds_total{instance=\"$node\"})))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\", instance=\"$node\"}[$__rate_interval])) / scalar(count(count by(cpu) (node_cpu_seconds_total{instance=\"$node\"})))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\", instance=\"$node\"}[$__rate_interval])) / scalar(count(count by(cpu) (node_cpu_seconds_total{instance=\"$node\"})))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\", instance=\"$node\"}[$__rate_interval])) / scalar(count(count by(cpu) (node_cpu_seconds_total{instance=\"$node\"})))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\"}[$__rate_interval])) / scalar(count(count by(cpu) (node_cpu_seconds_total{instance=\"$node\"})))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\", instance=\"$node\"}[$__rate_interval])) / scalar(count(count by(cpu) (node_cpu_seconds_total{instance=\"$node\"})))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])) / scalar(count(count by(cpu) (node_cpu_seconds_total{instance=\"$node\"})))",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_guest_seconds_total{instance=\"$node\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\"}[$__rate_interval]))) > 0",
     "legendFormat": "Guest CPU usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "RAM and swap usage overview, including caches",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\", job=\"kubernetes-pods\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\", job=\"kubernetes-pods\"} - node_memory_MemFree_bytes{instance=\"$node\", job=\"kubernetes-pods\"} - (node_memory_Cached_bytes{instance=\"$node\", job=\"kubernetes-pods\"} + node_memory_Buffers_bytes{instance=\"$node\", job=\"kubernetes-pods\"} + node_memory_SReclaimable_bytes{instance=\"$node\", job=\"kubernetes-pods\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\", job=\"kubernetes-pods\"} + node_memory_Buffers_bytes{instance=\"$node\", job=\"kubernetes-pods\"} + node_memory_SReclaimable_bytes{instance=\"$node\", job=\"kubernetes-pods\"}",
     "legendFormat": "Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\", job=\"kubernetes-pods\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\", job=\"kubernetes-pods\"} - node_memory_SwapFree_bytes{instance=\"$node\", job=\"kubernetes-pods\"})",
     "legendFormat": "Swap used"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "description": "Percentage of filesystem space used for each mounted device",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{job=\"$job\", device!~\"rootfs\"} - node_filesystem_avail_bytes{job=\"$job\", device!~\"rootfs\"}) / node_filesystem_size_bytes{job=\"$job\", device!~\"rootfs\"}) * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Space Fast- & Slow-Datadir",
   "type": "timeseries",
   "description": "Percentage of filesystem space used for each mounted device",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((kaapana_fast_fs_size_bytes{custom_job_name=\"node-exporter\"} - kaapana_fast_fs_available_bytes{custom_job_name=\"node-exporter\"}) / kaapana_fast_fs_size_bytes{custom_job_name=\"node-exporter\"}) * 100",
     "legendFormat": "fast-datadir-path: {{path}}"
    },
    {
     "expr": "((kaapana_slow_fs_size_bytes{custom_job_name=\"node-exporter\"} - kaapana_slow_fs_available_bytes{custom_job_name=\"node-exporter\"}) / kaapana_slow_fs_size_bytes{custom_job_name=\"node-exporter\"}) * 100",
     "legendFormat": "slow-datadir-path: {{path}}"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Nvidia Driver",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by(DCGM_FI_DRIVER_VERSION) (1, DCGM_FI_DEV_GPU_TEMP{instance=\"nvidia-dcgm-exporter.gpu-operator-resources.svc:9400\", Hostname=\"$hostname\", gpu=\"$gpu\"})",
     "legendFormat": "{{DCGM_FI_DRIVER_VERSION}}"
    }
   ]
  },
  {
   "title": "Available GPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 2, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=\"nvidia-dcgm-exporter.gpu-operator-resources.svc:9400\", Hostname=\"$hostname\"}",
     "legendFormat": "GPU-{{gpu}}, device: {{device}}, Type: {{modelName}}"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=\"nvidia-dcgm-exporter.gpu-operator-resources.svc:9400\", gpu=\"$gpu\"} + DCGM_FI_DEV_FB_FREE{instance=\"nvidia-dcgm-exporter.gpu-operator-resources.svc:9400\", gpu=\"$gpu\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=\"nvidia-dcgm-exporter.gpu-operator-resources.svc:9400\", gpu=\"$gpu\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "DCGM_FI_DEV_FB_FREE{instance=\"nvidia-dcgm-exporter.gpu-operator-resources.svc:9400\", gpu=\"$gpu\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "GPU Clockspeed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{instance=\"nvidia-dcgm-exporter.gpu-operator-resources.svc:9400\", gpu=\"$gpu\"} * 1000000",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}