"""add external_id to task_runs

Revision ID: 164ae9d77584
Revises: 8a1bbba894ad
Create Date: 2025-09-04 07:01:21.909492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164ae9d77584'
down_revision: Union[str, None] = '8a1bbba894ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_runs', sa.Column('external_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_runs', 'external_id')
    # ### end Alembic commands ###
