"""change task_identifier to task title

Revision ID: 8a1bbba894ad
Revises: 1a9377b8a612
Create Date: 2025-09-01 08:34:48.706985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1bbba894ad'
down_revision: Union[str, None] = '1a9377b8a612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.String(), nullable=True))
    op.drop_index(op.f('ix_tasks_task_identifier'), table_name='tasks')
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.drop_column('tasks', 'task_identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_identifier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.create_index(op.f('ix_tasks_task_identifier'), 'tasks', ['task_identifier'], unique=False)
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###
