FROM local-only/dag-installer:0.1.0

LABEL IMAGE="dag-tfda-execution-orchestrator"
LABEL VERSION="0.0.1"
LABEL CI_IGNORE="False"

COPY dags/dag_tfda_execution_orchestrator.py /tmp/dags/
COPY dags/tfda_execution_orchestrator /tmp/dags/tfda_execution_orchestrator
