FROM local-only/base-installer:latest

LABEL IMAGE="dag-extract-scanparameters"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY files/dag_extract_scanparameter.py /kaapana/tmp/dags/
COPY files/extract_scanparameter /kaapana/tmp/dags/extract_scanparameter