FROM local-only/dag-installer:latest

LABEL IMAGE="dag-extract-scanparameters"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY files/dag_extract_scanparameter.py /temp/dags/
COPY files/extract_scanparameter /temp/dags/extract_scanparameter