FROM local-only/charts-manager:0.1.0

LABEL IMAGE="kaapana-exp-extensions"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

## following code line needs to be uncommented if new charts are added as experimental extensions. Currently "kaapana/services/extensions-manager/kaapana-extensions/kaapana-exp-extensions/docker/files/requirements.yaml file is empty and therefore no charts would be created under /files/charts folder.
# COPY files/charts /tmp 
