FROM local-only/dag-installer:0.1.0

LABEL IMAGE="dag-nnunet-inference"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY dags/nnunet /tmp/dags/nnunet
COPY dags/dag_nnunet_inference.py /tmp/dags/
# COPY dags/dag_download_all_models.py /tmp/dags/