---
dependencies:
  - name: kaapana-platform-chart
    version: 0.0.0
  - name: dev-code-server-chart
    version: 0.0.0
  - name: code-server-chart
    version: 0.0.0
  - name: kaapana-workflows-core
    version: 0.0.0