import { kaapanaIcons } from '@kaapana/base-ui'

export const icons = {
  ...kaapanaIcons,
  entity: 'mdi-database',
  zoomIn: 'mdi-magnify-plus-outline',
  zoomOut: 'mdi-magnify-minus-outline',
  schemas: 'mdi-file-document-multiple-outline',
  maintenance: 'mdi-broom',
  shortcuts: 'mdi-keyboard-outline',
  filter: 'mdi-filter-outline',
  filterOff: 'mdi-filter-off',
  filterActive: 'mdi-filter-check',
  copy: 'mdi-content-copy',
  paste: 'mdi-clipboard-arrow-down-outline',
  preview: 'mdi-eye-outline',
  download: 'mdi-download',
  noImage: 'mdi-image-off-outline',
  metadata: 'mdi-file-document-outline',
  storage: 'mdi-database-outline',
  hierarchy: 'mdi-file-tree',
  artifacts: 'mdi-paperclip',
  parent: 'mdi-arrow-up',
  child: 'mdi-subdirectory-arrow-right',
  addGroupAnd: 'mdi-set-merge',
  addGroupOr: 'mdi-set-split',
  visual: 'mdi-format-list-bulleted',
  json: 'mdi-code-tags',
  collapse: 'mdi-chevron-up',
} as const
