/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreAdminOverview: typeof import('./components/TreAdminOverview.vue')['default']
    TreApply: typeof import('./components/TreApply.vue')['default']
    TreBase: typeof import('./components/TreBase.vue')['default']
    TreOpenRequests: typeof import('./components/TreOpenRequests.vue')['default']
    TreUserOverview: typeof import('./components/TreUserOverview.vue')['default']
    TtreUserOverview: typeof import('./components/TtreUserOverview.vue')['default']
  }
}
