---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extensions-ui
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: extensions-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: extensions-ui
    spec:
      containers:
      - name: extensions-ui
        image: "{{ .Values.global.registry_url }}/extensions-ui:{{ .Values.global.kaapana_build_version }}"
        imagePullPolicy: "{{ .Values.global.pull_policy_images }}"
        ports:
        - name: http-port
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: http-port
          initialDelaySeconds: 10
          periodSeconds: 20
        resources:
          requests:
            memory: "10Mi"
          limits:
            memory: "100Mi"
        volumeMounts:
          - name: tmp
            mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      volumes:
      - name: tmp
        emptyDir: {}
      priorityClassName: kaapana-high-priority
      imagePullSecrets:
        - name: registry-secret
