FROM local-only/base-installer:latest

LABEL IMAGE="dag-add-external-pacs"
LABEL VERSION="0.1.0"
LABEL BUILD_IGNORE="False"

COPY files/dag_add_external_pacs.py /kaapana/tmp/dags/
COPY files/add_external_pacs /kaapana/tmp/dags/add_external_pacs