{{- if .Values.global.gpu_support }}
---
apiVersion: v1
kind: Service
metadata:
  name: nninteractive-server-service
  namespace: "{{ .Values.global.services_namespace }}"
  labels:
    app.kubernetes.io/name: nninteractive-server
    app.kubernetes.io/part-of: nninteractive-ohif
spec:
  selector:
    app.kubernetes.io/name: nninteractive-server
  ports:
    - name: nninteractive
      port: {{ .Values.nninteractiveServer.port }}
      targetPort: {{ .Values.nninteractiveServer.port }}
      protocol: TCP
  type: ClusterIP
{{- end }}
