{{- $ns := .Values.global.services_namespace }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaapana-kube-admin
  namespace: {{ $ns }}

############################
# RBAC
############################
{{- if not .Values.global.managed_kubernetes }}
---
# ClusterRoleBinding (self-managed)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-crb-{{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kaapana-kube-admin
    namespace: {{ $ns }}

{{- else }}

{{- range $all_ns := .Values.global.all_managed_namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaapana-services-ns
  namespace: {{ $all_ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kaapana-admin-ns
subjects:
- kind: ServiceAccount
  name: kaapana-kube-admin
  namespace: {{ $ns }}
{{- end }}

{{- end }}