FROM docker.io/dcm4che/dcm4chee-arc-psql:5.26.0

LABEL IMAGE="dcm4chee-arc"
LABEL VERSION="5.26.0"
LABEL CI_IGNORE="False"

COPY files/dcm4chee-arc.xml /docker-entrypoint.d/configuration/dcm4chee-arc.xml