FROM docker.io/dcm4che/dcm4chee-arc-psql:5.32.0
LABEL IMAGE="dcm4chee-arc"
LABEL VERSION="5.32.0"
LABEL BUILD_IGNORE="False"

RUN apt update && apt upgrade -y binutils binutils-common binutils-x86-64-linux-gnu curl libbinutils libc-bin libc6 libctf-nobfd0 libctf0 libcurl4 libgnutls30 libpam-modules libpam-modules-bin libpam-runtime libpam0g libsqlite3-0 libssh-4 libssh-gcrypt-4 locales tar