FROM local-only/base-installer:latest

LABEL IMAGE="dag-mitk-flow"
LABEL VERSION="2022.10"
LABEL CI_IGNORE="False"

COPY files/dag_mitk_flow.py /kaapana/tmp/dags/
COPY files/mitk_flow /kaapana/tmp/dags/mitk_flow
