"""v0-4-2

Revision ID: b2c8d2f8b682
Revises:
Create Date: 2025-03-27 13:51:51.201408

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2c8d2f8b682"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dicom_data",
        sa.Column("series_instance_uid", sa.String(), nullable=False),
        sa.Column("study_instance_uid", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("series_instance_uid"),
    )
    op.create_table(
        "data_projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("series_instance_uid", sa.String(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["series_instance_uid"],
            ["dicom_data.series_instance_uid"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "series_instance_uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_projects")
    op.drop_table("dicom_data")
    # ### end Alembic commands ###
