export const PURGE_AUTH = 'logOut'
export const SET_AUTH = 'setUser'
export const SET_ERROR = 'setError'
export const SET_AVAILABLE_WEBISTES = 'setAvailableWebsites'
export const SET_COMMON_DATA = 'set_common_data'
export const SET_POLICY_DATA = 'set_policy_data'
export const SET_SELECTED_PROJECT = 'set_selected_project'
export const SET_AVAILABLE_PROJECTS = 'set_available_project'