FROM local-only/base-installer:latest

LABEL IMAGE="dag-rename-seg-label-names"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY files/dag_rename_seg_label_names.py /kaapana/tmp/dags/
COPY files/rename_seg_label_names /kaapana/tmp/dags/rename_seg_label_names