FROM local-only/dag-installer:latest

LABEL IMAGE="dag-bodypartregression"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY files/dag_bodypartregression.py /temp/dags/
COPY files/bodypartregression /temp/dags/bodypartregression