apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .Values.global.vmName }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    template-version.harvesterhci.io/customName: dlUygmXvUO
    harvesterhci.io/enableCPUAndMemoryHotplug: "true"
    harvesterhci.io/volumeClaimTemplates: >-
      [
        {
          "metadata": { "name": "{{ .Values.global.vmName }}-disk-0", "annotations": { "harvesterhci.io/imageId": "harvester-public/image-m4ds5" } },
          "spec": {
            "accessModes": ["ReadWriteMany"],
            "resources": { "requests": { "storage": "{{ .Values.global.diskSize }}" } },
            "volumeMode": "Block",
            "storageClassName": "px-fa-direct-access"
          }
        }
      ]
    network.harvesterhci.io/ips: '[]'
  labels:
    template.harvesterhci.io/templateID: dkfz-ubuntu-24
    harvesterhci.io/os: ubuntu
    harvesterhci.io/creator: harvester
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '["kaapana-develop/kaapana"]'
      labels:
        harvesterhci.io/vmName: {{ .Values.global.vmName }}
    spec:
      domain:
        cpu:
          cores: {{ .Values.global.cpuCores }}
          maxSockets: 1
          sockets: 1
          threads: 1
        memory:
          guest: {{ .Values.global.memoryGuest }}
        devices:
          disks:
            - name: disk-0
              bootOrder: 1
              disk:
                bus: virtio
            - disk:
                bus: virtio
              name: cloudinitdisk
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - bridge: {}
              model: virtio
              name: default
        features:
          acpi:
            enabled: true
        machine:
          type: q35
        resources:
          limits:
            cpu: "{{ .Values.global.cpuCores }}"
            memory: "{{ .Values.global.memoryGuest }}"
      evictionStrategy: LiveMigrateIfPossible
      networks:
        - name: default
          multus:
            networkName: harvester-public/dkfz-net
      terminationGracePeriodSeconds: 120
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: {{ .Values.global.vmName }}-disk-0
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: {{ .Values.global.vmName }}-cloudinit
      hostname: {{ .Values.global.vmName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.vmName }}-cloudinit
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  userdata: |
    #cloud-config
    package_update: true
    packages:
      - qemu-guest-agent
    runcmd:
      - systemctl enable --now qemu-guest-agent.service
    ssh_authorized_keys:
      - {{ .Values.global.publicKey }}
  networkdata: |
    version: 2
    ethernets: {}
      