# generated by datamodel-codegen:
#   filename:  ContainerEnvVar.schema.json

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel


class Type(Enum):
    boolean = "boolean"
    string = "string"
    int = "int"


class TaskTemplateEnv(BaseModel):
    name: str
    value: str
    type: Optional[Type] = None
    choices: Optional[List[str]] = None
    adjustable: Optional[bool] = None
    description: Optional[str] = None
