# generated by datamodel-codegen:
#   filename:  TaskTemplate.schema.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel

from . import IOMount_schema, Resources_schema, TaskTemplateEnv_schema


class TaskTemplate(BaseModel):
    """
    Blueprint for how a Docker image can be used for data processing in a predefined way.
    """

    identifier: str
    description: str
    command: List[str]
    inputs: List[IOMount_schema.IOMount]
    outputs: List[IOMount_schema.IOMount]
    env: List[TaskTemplateEnv_schema.TaskTemplateEnv]
    resources: Optional[Resources_schema.Resources] = None
