{
 "title": "RACOON Site Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site_instance",
    "label": "Site",
    "query": {
     "query": "label_values(build_info,instance)"
    }
   },
   { "name": "component", "label": "Node Software Component", "query": { "query": "label_values(build_info,job)" } }
  ]
 },
 "panels": [
  {
   "title": "Basic Infos",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "build_info{instance=\"$site_instance\",job=\"$component\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "barchart",
   "gridPos": { "h": 21, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "uptime{instance=\"$site_instance\",job=\"$component\"}",
     "legendFormat": " $component Uptime"
    }
   ]
  },
  {
   "title": "OS Storage Usage",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storage_size_1_free{instance=\"$site_instance\",job=\"$component\"}",
     "legendFormat": "OS Storage Free"
    },
    {
     "expr": "storage_size_1_total{instance=\"$site_instance\",job=\"$component\"} - storage_size_1_free{instance=\"$site_instance\",job=\"$component\"}",
     "legendFormat": "OS Storage Used"
    }
   ]
  },
  {
   "title": "Date Storage Usage",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storage_size_0_total{instance=\"$site_instance\",job=\"$component\"} - storage_size_0_free{instance=\"$site_instance\",job=\"$component\"}",
     "legendFormat": "Data Storage Used"
    },
    {
     "expr": "storage_size_0_free{instance=\"$site_instance\",job=\"$component\"}",
     "legendFormat": "Data Storage Free"
    }
   ]
  }
 ]
}