FROM local-only/dag-installer:latest

LABEL IMAGE="dag-nnunet-federated"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY files/dag_nnunet_federated.py /tmp/dags/
COPY files/nnunet_federated /tmp/dags/nnunet_federated
