FROM local-only/base-python-cpu:latest

LABEL IMAGE="python-template" 
#"example-extract-study-id"
LABEL VERSION="0.1.0"
LABEL BUILD_IGNORE="False"
#if BUILD_IGNORE is True, Docker Image will not be built automatically by the build script
