FROM local-only/base-python-alpine:latest

LABEL IMAGE="python-template" 
#"example-extract-study-id"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"
#if CI_IGNORE is True, Docker Image will not be build automatically by the build script
