# generated by datamodel-codegen:
#   filename:  ContainerEnvVar.schema.json

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class Type(Enum):
    boolean = 'boolean'
    string = 'string'
    int = 'int'


class ContainerEnvVar(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    value: str
    type: Optional[Type] = None
    choices: Optional[List[str]] = None
    adjustable: Optional[bool] = None
    description: Optional[str] = None
