# generated by datamodel-codegen:
#   filename:  IOMount.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel

from . import ScaleRule_schema


class IOMount(BaseModel):
    name: str
    mounted_path: str
    description: Optional[str] = None
    scale_rule: Optional[ScaleRule_schema.ScaleRule] = None
