# generated by datamodel-codegen:
#   filename:  IOVolume.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel

from . import LocalPath_schema, ScaleRule_schema


class IOVolume(BaseModel):
    """
    Represents a storage location for input/output data.
    """

    name: str
    scale_rule: Optional[ScaleRule_schema.ScaleRule] = None
    input: LocalPath_schema.LocalPath
