# generated by datamodel-codegen:
#   filename:  ProcessingContainer.schema.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel

from . import TaskTemplate_schema


class ProcessingContainer(BaseModel):
    """
    Defines a processing unit that bundles multiple task templates under a single container concept.
    """

    name: str
    description: str
    templates: List[TaskTemplate_schema.TaskTemplate]
