# generated by datamodel-codegen:
#   filename:  ProcessingContainer.schema.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel

from . import TaskTemplate_schema


class ProcessingContainer(BaseModel):
    name: str
    description: str
    templates: List[TaskTemplate_schema.TaskTemplate]
