# generated by datamodel-codegen:
#   filename:  TaskRun.schema.json

from __future__ import annotations

from .TaskInstance_schema import TaskInstance


class TaskRun(TaskInstance):
    id: str
    mode: str
