# generated by datamodel-codegen:
#   filename:  Task.schema.json

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel

from . import (
    ContainerEnvVar_schema,
    IOVolume_schema,
    ProcessingContainer_schema,
    Resources_schema,
)


class Task(BaseModel):
    name: str
    image: str
    taskTemplate: Union[str, ProcessingContainer_schema.ProcessingContainer]
    command: Optional[List[str]] = None
    inputs: List[IOVolume_schema.IOVolume]
    outputs: List[IOVolume_schema.IOVolume]
    env: Optional[List[ContainerEnvVar_schema.ContainerEnvVar]] = []
    resources: Optional[Resources_schema.Resources] = None
    namespace: Optional[str] = None
    registryUrl: Optional[str] = None
    registryUsername: Optional[str] = None
    registryPassword: Optional[str] = None
    imagePullSecrets: Optional[List[str]] = None
