# generated by datamodel-codegen:
#   filename:  TaskInstance.schema.json

from __future__ import annotations

from typing import List, Optional

from . import IOChannel_schema
from .Task_schema import Task
from .TaskTemplate_schema import TaskTemplate


class TaskInstance(Task, TaskTemplate):
    """
    A resolved task, created by merging the Task definition with its associated TaskTemplate.
    """

    inputs: Optional[List[IOChannel_schema.IOChannel]] = None
    outputs: Optional[List[IOChannel_schema.IOChannel]] = None
