# generated by datamodel-codegen:
#   filename:  TaskTemplates.schema.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel

from . import ProcessingContainer_schema


class TaskTemplates(BaseModel):
    name: str
    description: str
    templates: List[ProcessingContainer_schema.ProcessingContainer]
