FROM local-only/base-installer:latest

LABEL IMAGE="dag-radiomics-federated"
LABEL VERSION="0.1.0"
LABEL BUILD_IGNORE="False"

COPY files/dag_radiomics_federated.py /kaapana/tmp/dags/
COPY files/radiomics_federated /kaapana/tmp/dags/radiomics_federated
