---
global:
  pull_policy_images: "IfNotPresent"
  hostname: ""
  fast_data_dir: /home/kaapana
  slow_data_dir: /home/kaapana
  dynamicVolumes:
  - name: models
    storage_class: workflow
    storage: 200Gi
  - name: workflow-data
    storage_class: workflow
    storage: 200Gi
  - name: uploads
    storage_class: workflow
    storage: 100Gi
  - name: af-plugins
    storage_class: workflow
    storage: 1Gi
  - name: dags
    storage_class: workflow
    storage: 1Gi
  - name: af-logs
    storage_class: workflow
    storage: 100Gi

kaapana_database:
  admin: false
  postgres_user: root
  postgres_password: root
  postgres_db: airflow
  appName: airflow
