FROM local-only/dag-installer:latest

LABEL IMAGE="dag-radiomics"
LABEL VERSION="0.1.1"
LABEL CI_IGNORE="False"

COPY files/dag_radiomics_dcmseg.py /temp/dags/
COPY files/radiomics /temp/dags/radiomics