FROM local-only/base-installer:latest

LABEL IMAGE="dag-radiomics"
LABEL VERSION="0.1.1"
LABEL CI_IGNORE="False"

COPY files/dag_radiomics_dcmseg.py /kaapana/tmp/dags/
COPY files/radiomics /kaapana/tmp/dags/radiomics