FROM local-only/dag-installer:0.1.0

LABEL IMAGE="dag-example-otsus-method"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="True"

COPY files/dag_example_otsus_method.py /tmp/dags/
COPY files/otsus-method/OtsusMethodOperator.py /tmp/dags/otsus_method/
