FROM local-only/dag-installer:0.1.0

LABEL IMAGE="dag-nnunet-federated"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY dags/dag_nnunet_federated.py /tmp/dags/
COPY dags/nnunet_federated /tmp/dags/nnunet_federated

COPY common/scripts/nnunet_federated /tmp/common/scripts/nnunet_federated