FROM local-only/dag-installer:0.1.0

LABEL IMAGE="dag-bodypartregression"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY dags/dag_bodypartregression.py /tmp/dags/
COPY dags/dag_bodypartregression_trigger_rule.json /tmp/dags/
COPY dags/bodypartregression /tmp/dags/bodypartregression