FROM busybox:1.31

LABEL IMAGE="dag-mitk-userflow"
LABEL VERSION="0.9-vdev"
LABEL CI_IGNORE="False"

COPY dags/dag_mitk_userflow.py /workflows/dags/
COPY dags/mitk_userflow /workflows/dags/mitk_userflow

CMD ["cp","-rf","/workflows/.","/mount_data/"]
