FROM local-only/dag-installer:0.1.0

LABEL IMAGE="dag-mitk-userflow"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY dags/dag_mitk_flow.py /tmp/dags/
COPY dags/mitk_userflow /tmp/dags/mitk_userflow
