FROM local-only/base-installer:latest

LABEL IMAGE="dag-modify-dcmseg"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY files/dag_modify_dcmseg.py /kaapana/tmp/dags/
COPY files/modify_dcmseg /kaapana/tmp/dags/modify_dcmseg