FROM local-only/base-installer:latest

LABEL IMAGE="dag-collect-bridgehead-metadata"
LABEL VERSION="0.0.0"
LABEL BUILD_IGNORE="False"

COPY files/dag_collect_bridgehead_metadata.py /kaapana/tmp/dags/
COPY files/bridgehead /kaapana/tmp/dags/bridgehead
