FROM local-only/dag-installer:latest

LABEL IMAGE="dag-shapemodel"
LABEL VERSION="0.1.1"
LABEL CI_IGNORE="False"

COPY files/dag_shapemodel_organ_seg.py /temp/dags/
COPY files/shapemodel /temp/dags/shapemodel
