FROM local-only/base-installer:latest

LABEL IMAGE="dag-shapemodel"
LABEL VERSION="0.1.1"
LABEL CI_IGNORE="False"

COPY files/dag_shapemodel_organ_seg.py /kaapana/tmp/dags/
COPY files/shapemodel /kaapana/tmp/dags/shapemodel
