import type { Settings } from '@/types/settings'

const settings: Settings = {
  // The views read darkMode. The shell derives it from themeMode and uses the
  // value here only when the browser's preference cannot be asked.
  darkMode: true,
  themeMode: 'system',
  devMode: false,
  landingPage: ['Patient Sex', 'Modality'],
  datasets: {
    structured: false,
    cols: 'auto',
    cardText: true,
    tagBar: {
      multiple: false,
      tags: [],
    },
    itemsPerPagePagination: 1000,
    sort: '00000000 TimestampArrived_datetime',
    sortDirection: 'desc',
    executeSlicedSearch: false,
    props: [
      {
        name: 'Series Description',
        display: true,
        truncate: true,
        dashboard: false,
        patientView: false,
        studyView: false,
      },
      {
        name: 'Patient ID',
        display: false,
        truncate: true,
        dashboard: false,
        patientView: false,
        studyView: false,
      },
      {
        name: 'Patient Name',
        display: true,
        truncate: true,
        dashboard: false,
        patientView: true,
        studyView: false,
      },
      {
        name: 'Patient Birth Date',
        display: false,
        truncate: true,
        dashboard: false,
        patientView: true,
        studyView: false,
      },
      {
        name: 'Patient Sex',
        display: true,
        truncate: true,
        dashboard: false,
        patientView: true,
        studyView: false,
      },
      {
        name: 'Study Description',
        display: true,
        truncate: true,
        dashboard: false,
        patientView: false,
        studyView: false,
      },
      {
        name: 'Study Date',
        display: true,
        truncate: true,
        dashboard: false,
        patientView: false,
        studyView: true,
      },
      {
        name: 'Modality',
        display: false,
        truncate: false,
        dashboard: true,
        patientView: true,
        studyView: true,
      },
      {
        name: 'Tags',
        display: false,
        truncate: false,
        dashboard: true,
        patientView: false,
        studyView: false,
      },
      {
        name: 'Manufacturer',
        display: false,
        truncate: false,
        dashboard: true,
        patientView: false,
        studyView: false,
      },
    ],
  },
}
export { settings }
