FROM local-only/dag-installer:0.1.0

LABEL IMAGE="kaapana-plugin"
LABEL VERSION="0.1.1-vdev"
LABEL CI_IGNORE="False"

COPY dags/dag_delete_series_from_platform.py /tmp/dags/

COPY dags/dag_download_selected_files.py /tmp/dags/
COPY dags/dag_service_extract_metadata.py /tmp/dags/
COPY dags/dag_collect_metadata.py /tmp/dags/
COPY dags/dag_send_dicom.py /tmp/dags/

COPY dags/dag_service_process_incoming_dcm.py /tmp/dags/
COPY dags/dag_service_minio_dicom_upload.py /tmp/dags/
COPY dags/dag_service_reindex_dicom_data.py /tmp/dags/
COPY dags/dag_service_clean_up_airflow_logs.py /tmp/dags
COPY dags/dag_service_sync_dag_db.py /tmp/dags/
COPY dags/dag_service_clean_tmp_dag_data.py /tmp/dags/

COPY plugins/ /tmp/plugins